#!/bin/sh
# (c) 2015, The MITRE Corporation. All rights reserved.
# Source code distributed pursuant to license agreement.
#
# Usage: script/bootstrap
# This script is designed to install all of the necessary dependencies for a
# CRITs install.


ARCH=$(uname -m | sed 's/x86_//;s/i[3-6]86/32/')
echo "Architecture: $ARCH"

if [ $ARCH -ne '64' ]; then
  echo "** Non 64-bit system detected **"
  echo "These dependencies are for a 64-bit system."
  echo "Exiting.."
  exit
fi

# Using lsb-release because os-release not available on Ubuntu 10.04
if [ -f /etc/lsb-release ]; then
  . /etc/lsb-release
  OS=$DISTRIB_ID
  VER=$DISTRIB_RELEASE
elif [ -f /etc/redhat-release ]; then
  OS=$(cat /etc/redhat-release | sed 's/ Enterprise.*//')
  VER=$(cat /etc/redhat-release | sed 's/.*release //;s/ .*$//')
else
  OS=$(uname -s)
  VER=$(uname -r)
fi

OS="$(tr "[:upper:]" "[:lower:]" <<< "$OS")"
VER="$(tr "[:upper:]" "[:lower:]" <<< "$VER")"

if [ "$OS" == 'ubuntu' ]
then
  echo "Installing dependencies with apt-get"
  sudo apt-get update
  sudo apt-get install -y --fix-missing apache2 build-essential curl git libapache2-mod-wsgi libevent-dev libz-dev libfuzzy-dev libldap2-dev libpcap-dev libpcre3-dev libsasl2-dev libxml2-dev libxslt1-dev libyaml-dev mongodb numactl p7zip-full python-dev python-pip ssdeep upx zip swig libssl-dev

# TODO: Need to test centos dependencies
# elif [ "$OS" == 'centos' ] || [ "$OS" == 'redhat' ]
elif [ "$OS" == 'red hat' ]
then
  echo "Installing Yum Packages"
  # Probably should run the Yum equivelent of apt-get update
  sudo yum install httpd mod_wsgi mod_ssl make gcc gcc-c++ kernel-devel pcre pcre-devel curl libpcap-devel python-pycurl python-dateutil python-devel python-setuptools

  echo "Automatically installing manual packages"
  sudo yum install zip unzip gzip bzip2
  sudo yum install p7zip-9.20.1-2
  sudo yum install unrar-4.2.3-1
  sudo yum install libyaml-0.1.4-1
  sudo yum install upx-3.07-1

elif [ "$OS" == 'darwin' ]
then
  command -v brew >/dev/null 2>&1 || {
    echo "Installation for OSX requires Homebrew. Please visit http://brew.sh/."
    exit
  }
  brew install mongodb ssdeep upx p7zip libyaml pcre libxml2 openssl
else
  echo "Unknown distro!"
  echo -e "Detected: $OS $VER"
  exit
fi

command -v mongo >/dev/null 2>&1 || {
  echo "Installing MongoDB 2.6.4..."
  curl http://downloads.mongodb.org/linux/mongodb-linux-x86_64-2.6.4.tgz > mongodb-linux-x86_64-2.6.4.tgz
  tar -zxvf mongodb-linux-x86_64-2.6.4.tgz
  sudo cp ./mongodb-linux-x86_64-2.6.4/bin/* /usr/local/bin/
  rm  mongodb-linux-x86_64-2.6.4.tgz
  rm -r mongodb-linux-x86_64-2.6.4
}

echo "Installing Python Dependencies"
sudo pip install -r requirements.txt

echo "Dependency installations complete!"
